version: '3.8'
services:
  smartmet-server:
    build: .
    image: test
    depends_on:
      redis:
        condition: service_healthy

    environment:
      - REDIS_CONTENT_SERVER_ADDRESS=redis
      - REDIS_CONTENT_SERVER_PORT=6379
      - REDIS_CONTENT_SERVER_TABLE_PREFIX=.smartmet
      - SMARTMET_ENV_FILE=/smartmet/smartmet.env
      - GRID_FILES_LIBRARY_CONFIG_FILE=/config/libraries/grid-files/grid-files.conf
      - GRID_FILE_STORAGE_DIR=
    cap_add:
      - ALL
    security_opt:
      - "seccomp=unconfined"
    command: '/usr/sbin/smartmetd --debug --configfile /config/server.conf --port 8080'
    # This should be visible in the host
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      # Main configuration file
      - ./conf/server.conf:/config/server.conf
      # Environment variables
      - ./conf/smartmet-backend.env:/smartmet/smartmet.env
      # Health check TODO put this to Dockerfile
      - ./conf/smartmet_alert.sh:/etc/smartmet/smartmet_alert.sh
      # Engine configuration
      - ./conf/engines/:/config/engines/
      # Plugin configuration
      - ./conf/plugins/:/config/plugins/
      # Library configuration
      - ./conf/libraries/:/config/libraries/
    restart: unless-stopped
    # This is the network between containers
    networks:
      - smartmetserver

  redis:
    image: redis:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    # This should be visible in the host
    ports:
      - "6380:6379"
    # This is the network between containers
    networks:
      - smartmetserver

  filesys2smartmet:
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_CONTENT_SERVER_ADDRESS=redis
      - REDIS_CONTENT_SERVER_PORT=6379
      - REDIS_CONTENT_SERVER_TABLE_PREFIX=smartmet.
      - MEMORYMAPPER_ENABLED=false
    image: quay.io/fmi/smartmet-server:filesys2smartmet-0.0.5
    command: '/usr/bin/fmi/filesys2smartmet /config/filesys2smartmet.conf 60'
    restart: unless-stopped
    volumes:
      - ./filesys2smartmet/conf/filesys2smartmet.conf:/config/filesys2smartmet.conf
      - ./filesys2smartmet/conf/libraries/:/config/libraries
      - ./filesys2smartmet/data/:/data/
    # This is the network between containers
    networks:
      - smartmetserver

networks:
  smartmetserver:
    name: smartmet-server
