version: '3'

services:
  smartmetserver:
    build: .
    image: fmidev/smartmetserver:latest
    ports:
      - "8080:8080"
    volumes:
      - model-fmi-meps:/smartmet/data/meps
    restart: unless-stopped
   meps-surface:
    image: fmidev/fmidownloader
    container_name: fmidownloader-meps-surface
    command:
      - "--producer=meps"
      - "--dir=surface"
      - "--filename=meps_europe_surface"
      - "--parameters=Temperature,DewPoint,Humidity,WindDirection,WindSpeedMS,WindGust,TotalCloudCover,Precipitation1h,WeatherSymbol3,Pressure,CAPE,CIN"
    volumes:
      - model-fmi-meps:/tmp
    restart: unless-stopped

volumes:
  model-fmi-meps:
    name: model-fmi-meps
