version: '3.8'
services:
  smartmetserver:
    build: .
    image: smartmetserver:latest
    command: '/usr/sbin/smartmetd --debug --configfile /smartmet/cnf/smartmetd/server.conf --port 8080'
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./conf/smartmet-server.conf:/smartmet/cnf/smartmetd/server.conf
      - ./conf/smartmet.env:/smartmet/smartmet.env
      - ./conf/smartmet_alert.sh:/etc/smartmet/smartmet_alert.sh
      - ./conf/plugins/:/smartmet/cnf/smartmetd/plugins
      - ./conf/engines/:/smartmet/cnf/smartmetd/engines
      - ./logs:/var/log/smartmet
    restart: unless-stopped

# konffit
# backend
# - sputnik fmi gitissä (generoidaan tai gitistä?)
# - etc/smartmet/smartmet.env määritellään käynnistys & portit yms systemd:lle --optiot
#  -c = CONFIGFILE=/smartmet/cnf/smartmetd/clients/backend.conf
# frontent

#configmap -> config tiedosto -> ajokomennolle