version: '3.8'
services:
  smartmet-server:
    build: .
    image: quay.io/fmi/smartmet-server:0.0.11
    environment:
      - REDIS_CONTENT_SERVER_ADDRESS=redis
      - REDIS_CONTENT_SERVER_PORT=6379
    command: '/usr/sbin/smartmetd --debug --configfile /smartmet/cnf/smartmetd/server.conf --port 8080'
    # This should be visible in the host
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      # Main configuration file
      - ./conf/server.conf:/smartmet/cnf/smartmetd/server.conf
      # Environment variables
      - ./conf/smartmet.env:/smartmet/smartmet.env
      # Health check TODO put this to Dockerfile
      - ./conf/smartmet_alert.sh:/etc/smartmet/smartmet_alert.sh
      # Engine configuration
      - ./conf/engines/:/smartmet/cnf/smartmetd/engines
      # Plugin configuration
      - ./conf/plugins/:/smartmet/cnf/smartmetd/plugins
      # Library configuration
      - ./conf/libraries/:/smartmet/cnf/smartmetd/libraries
    restart: unless-stopped
    # This is the network between containers
    networks:
      - smartmetserver

  redis:
    image: redis:latest
    restart: unless-stopped
    # This should be visible in the host
    ports:
      - "6380:6379"
    # This is the network between containers
    networks:
      - smartmetserver

  filesys2smartmet:
    environment:
      - REDIS_CONTENT_SERVER_ADDRESS=redis
      - REDIS_CONTENT_SERVER_PORT=6379
      - REDIS_CONTENT_SERVER_TABLE_PREFIX=smartmet.
      - GRID_FILES_LIBRARY_CONFIG_FILE=/config/grid-files.conf
      - GRID_TOOLS_CONFIG_DIR=/config/
    image: quay.io/fmi/smartmet-server:filesys2smartmet-0.0.2
    command: '/usr/bin/fmi/filesys2smartmet /config/filesys2smartmet/filesys2smartmet.conf 60'
    restart: unless-stopped
    volumes:
      - ./filesys2smartmet/conf/:/config/filesys2smartmet
      - ./filesys2smartmet/data/:/data/
    # This is the network between containers
    networks:
      - smartmetserver

networks:
  smartmetserver:
    name: smartmet-server


# konffit
# backend
# - sputnik fmi gitissä (generoidaan tai gitistä?)
# - etc/smartmet/smartmet.env määritellään käynnistys & portit yms systemd:lle --optiot
#  -c = CONFIGFILE=/smartmet/cnf/smartmetd/clients/backend.conf
# frontent

#configmap -> config tiedosto -> ajokomennolle
