version: '3.8'
services:
  smartmet-server:
#    build: .
    image: quay.io/fmi/smartmet-server:ext-seaheat-smartmet-server-0.1.8
    depends_on:
      redis:
        condition: service_healthy

    environment:
      - REDIS_CONTENT_SERVER_ADDRESS=redis
      - REDIS_CONTENT_SERVER_PORT=6379
      - REDIS_CONTENT_SERVER_TABLE_PREFIX=smartmet.
      - SMARTMET_ENV_FILE=/smartmet/smartmet.env
      - GRID_FILES_LIBRARY_CONFIG_FILE=/config/libraries/grid-files/grid-files.conf
      - GRID_FILE_STORAGE_DIR=
      - GRID_ENGINE_CONFIG_DIR=/config/engines/grid-engine
      - FMINAMES_USER=${FMINAMES_USER}
      - FMINAMES_PASSWORD=${FMINAMES_PASSWORD}
      - FMINAMES_HOST=${FMINAMES_HOST}
      - FMINAMES_DATABASE=${FMINAMES_DATABASE}
      - GIS_USER=${GIS_USER}
      - GIS_PASSWORD=${GIS_PASSWORD}
      - GIS_HOST=${GIS_HOST}
      - GIS_DATABASE=${GIS_DATABASE}


#    cap_add:
#      - ALL
    security_opt:
      - "seccomp=unconfined"
    command: bash -c "sleep 60; /usr/sbin/smartmetd --debug --configfile /config/server.conf --port 8080"
    # This should be visible in the host
    ports:
      - "8088:8080"
      - "8089:8081"
    volumes:
      # Main configuration file
      - ./conf/server.conf:/config/server.conf
      # Environment variables
      - ./conf/smartmet-backend.env:/smartmet/smartmet.env
      # Health check TODO put this to Dockerfile
      - ./conf/smartmet_alert.sh:/etc/smartmet/smartmet_alert.sh
      # Engine configuration
      - ./conf/engines/:/config/engines/
      # Plugin configuration
      - ./conf/plugins/:/config/plugins/
      # Library configuration
      - ./conf/libraries/:/config/libraries/
      # Mandatory WMS configuration paths
      - ./conf/wms-layer-conf:/config/wms-layer-conf
      # Data location TODO change this when deploying to Openshift
      - ./data/:/ext-seaheat-data/
    restart: unless-stopped
    # This is the network between containers
    networks:
      - smartmetserver

  smartmet-server-test-db:
    image: fmidev/smartmet-server-test-db:latest
    restart: unless-stopped
    networks:
      - smartmetserver

  redis:
    image: redis:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 10s
    # This should be visible in the host
    ports:
      - "6379:6379"
    # This is the network between containers
    networks:
      - smartmetserver

  filesys2smartmet:
    depends_on:
      redis:
        condition: service_healthy
    security_opt:
      - "seccomp=unconfined"
    environment:
      - REDIS_CONTENT_SERVER_ADDRESS=redis
      - REDIS_CONTENT_SERVER_PORT=6379
      - REDIS_CONTENT_SERVER_TABLE_PREFIX=smartmet.
      - MEMORYMAPPER_ENABLED=true
    image: quay.io/fmi/smartmet-server:filesys2smartmet-0.1.7
    command: '/usr/bin/fmi/filesys2smartmet /config/filesys2smartmet.conf 60'
    restart: unless-stopped
    volumes:
#      - ./filesys2smartmet/conf/filesys2smartmet.conf:/config/filesys2smartmet.conf
#      - ./filesys2smartmet/conf/libraries/:/config/libraries
      - ./data/:/ext-seaheat-data/
    # This is the network between containers
    networks:
      - smartmetserver

networks:
  smartmetserver:
    name: smartmet-server
