version: '3.8'
services:
  smartmetserver:
    build: .
    image: smartmetserver:latest
    ports:
      - "8080:8080"
    volumes:
      - ./conf/backend.cfg:/smartmet/cnf/smartmetd/clients/backend.conf
      - ./conf/smartmet.env:/smartmet/smartmet.env
      - ./conf/smartmet_alert.sh:/etc/smartmet/smartmet_alert.sh
      - ./logs:/var/log/smartmet
    restart: unless-stopped

# konffit
# backend
# - sputnik fmi gitissä (generoidaan tai gitistä?)
# - etc/smartmet/smartmet.env määritellään käynnistys & portit yms systemd:lle --optiot
#  -c = CONFIGFILE=/smartmet/cnf/smartmetd/clients/backend.conf
# frontent

#configmap -> config tiedosto -> ajokomennolle